@ECHO OFF
::---------------------------------------------------------------------
:: Gradle startup script for Windows
::
:: Generated by the Gradle wrapper.
::---------------------------------------------------------------------

IF "%JAVA_HOME%" == "" GOTO findFromPath
SET JAVA_EXE=%JAVA_HOME%\bin\java.exe
GOTO ok
:findFromPath
SET JAVA_EXE=java
:ok

SET PRG=%~dp0
SET CLASSPATH=%PRG%\gradle\wrapper\gradle-wrapper.jar

"%JAVA_EXE%" -cp "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*

