#!/usr/bin/env sh
################################################################################
# Gradle start up script for UN*X
#
# Generated by the Gradle wrapper.
################################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS="-Xmx64m"

app_name="Gradle"

# Determine the real path to this script, resolving symlinks.
PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`"/$link"
  fi
done

PRG_DIR=`dirname "$PRG"`

# Default location of the gradle home relative to the current script
GRADLE_HOME="$PRG_DIR/.gradle-wrapper"

CLASSPATH="$PRG_DIR/gradle/wrapper/gradle-wrapper.jar"

if [ -z "$JAVA_HOME" ]; then
  JAVA_CMD=`which java 2>/dev/null`
else
  JAVA_CMD="$JAVA_HOME/bin/java"
fi

if [ -z "$JAVA_CMD" ]; then
  echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
  exit 1
fi

# Build the command line
CMD="$JAVA_CMD $DEFAULT_JVM_OPTS -cp \"$CLASSPATH\" org.gradle.wrapper.GradleWrapperMain $@"

# Execute the command
exec $CMD

